seed: ${..seed}
algo: PPO

network:
  mlp:
    units: [512, 256, 128]
  separate_value_mlp: True

ppo:
  name: ${resolve_default:AllegroHand,${...experiment}}
  multi_gpu: ${...multi_gpu}
  normalize_input: True
  normalize_value: True
  value_bootstrap: True
  num_actors: ${...task.env.numEnvs}
  reward_scale_value: 0.01
  clip_value_loss: False
  normalize_advantage: True
  gamma: 0.99
  tau: 0.95
  learning_rate: 5e-4
  lr_schedule: kl  # 'fixed' | 'linear' | 'kl' | 'cos'
  kl_threshold: 0.016
  save_best_after: 500
  save_frequency: 200
  grad_norm: 1.0
  entropy_coef: 0.0
  truncate_grads: True
  e_clip: 0.2
  horizon_length: 8
  minibatch_size: 32768
  mini_epochs: 5
  critic_coef: 4
  clip_value: True
  bounds_loss_coef: 0.0001
  max_agent_steps: 700000000